name: Run Upload to PyPi on Push into master

on:
  push:
    branches:
      - master

jobs:
  upload_to_pypi:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Build and Upload to PyPi
      run: |
        python setup.py sdist bdist_wheel
        twine upload --username __token__ --password ${{ secrets.PYPI_API_TOKEN }} dist/*
